version: '3.8'

services:
  postgre:
    image: postgres:12
    container_name: postgre
    ports:
      - 5432:5432
    volumes:
      - postgre-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
volumes: 
  postgre-data: