export enum CommandType {
  HELP = 'help',
  EXIT = 'exit',
  CREATE_USER = 'create-user',
  GET_USERS = 'get-users',
  GET_USER = 'get-user',
  UPDATE_USER = 'update-user',
  DELETE_USER = 'delete-user',
  CREATE_BANK = 'create-bank',
  GET_BANKS = 'get-banks',
  GET_BANK = 'get-bank',
  UPDATE_BANK = 'update-bank',
  DELETE_BANK = 'delete-bank',
  CREATE_ACCOUNT = 'create-account',
  GET_ACCOUNTS = 'get-accounts',
  GET_ACCOUNT = 'get-account',
  GET_ALL_ACCOUNTS_BY_USER = 'get-all-accounts-by-user',
  GET_ALL_ACCOUNTS_BY_BANK = 'get-all-accounts-by-bank',
  GET_ALL_ACCOUNTS_BY_USER_AND_BANK = 'get-all-accounts-by-user-and-bank',
  UPDATE_ACCOUNT = 'get-account',
  DELETE_ACCOUNT = 'get-account',
  CREATE_TRANSACTION = 'create-transaction',
  GET_TRANSACTIONS = 'get-all-transactions',
  GET_TRANSACTION = 'get-transaction',
  GET_ALL_TRANSACTIONS_BY_ACCOUNT = 'get-all-transactions-by-account',
}
