export enum CommandName {
  HELP = 'help',
  EXIT = 'exit',
  CREATE_ACCOUNT = 'account-create',
  CREATE_BANK = 'bank-create',
  CREATE_TRANSACTION = 'transaction-create',
  CREATE_USER = 'user-create',
  DELETE_ACCOUNT = 'account-delete',
  DELETE_BANK = 'bank-delete',
  DELETE_USER = 'user-delete',
  GET_ACCOUNT = 'account-get',
  GET_ACCOUNTS = 'account-get-all',
  GET_ALL_ACCOUNTS_BY_BANK = 'account-get-all-by-bank',
  GET_ALL_ACCOUNTS_BY_USER_AND_BANK = 'account-get-all-by-user-and-bank',
  GET_ALL_ACCOUNTS_BY_USER = 'account-get-all-by-user',
  GET_ALL_BANK_USERS = 'bank-get-all-users',
  GET_ALL_TRANSACTIONS_BY_ACCOUNT = 'transaction-get-all-by-account',
  GET_ALL_USER_BANKS = 'user-get-all-banks',
  GET_BANK = 'bank-get',
  GET_BANKS = 'bank-get-all',
  GET_TRANSACTION = 'transaction-get',
  GET_TRANSACTIONS = 'transaction-get-all',
  GET_USER = 'user-get',
  GET_USERS = 'user-get-all',
  UPDATE_ACCOUNT = 'account-update',
  UPDATE_BANK = 'bank-update',
  UPDATE_USER = 'user-update',
}
